apiVersion: v1
kind: Template
metadata:
  name: wheel-agent
parameters:
  - name: AGENT_NAMESPACE
    displayName: Namespace where the Wheel Agent is running.
    value: "wheel"
    required: true
  - name: CONFIG_REPOSITORY_URL
    displayName: Wheel Config Repository URL
    value: "https://github.com/wheel-sh/demo-cluster-config.git"
    required: true
  - name: CONFIG_REPOSITORY_BRANCH
    displayName: Git Branch
    value: "master"
    required: true
  - name: WHEEL_IMAGE
    displayName: Container image
    value: "registry.cloud.nikio.io/cicd/wheel-agent:latest"
    required: true
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: wheel-agent
      name: wheel-agent
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: wheel-agent
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: wheel-agent
      name: wheel-agent
      namespace: wheel
    spec:
      replicas: 1
      selector:
        app: wheel-agent
        deploymentconfig: wheel-agent
      template:
        metadata:
          labels:
            app: wheel-agent
            deploymentconfig: wheel-agent
        spec:
          serviceAccount: wheel-agent
          serviceAccountName: wheel-agent
          containers:
            - env:
                - name: CONFIG_REPOSITORY_URL
                  value: ${CONFIG_REPOSITORY_URL}
                - name: CONFIG_REPOSITORY_BRANCH
                  value: ${CONFIG_REPOSITORY_BRANCH}
              imagePullPolicy: Always
              name: wheel-agent
              image: ${WHEEL_IMAGE}
              ports:
                - containerPort: 8080
                  protocol: TCP
              volumeMounts:
                - mountPath: /.kube
                  name: kubeconfig
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: '1'
                  memory: 512Mi
                requests:
                  cpu: 500m
                  memory: 256Mi
          volumes:
            - name: kubeconfig
              emptyDir: {}
      triggers:
        - type: ConfigChange
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: wheel-agent
      name: wheel-agent
    spec:
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
      to:
        kind: Service
        name: wheel-agent
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: wheel-agent
  - apiVersion: authorization.openshift.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: self-access-reviewer-${AGENT_NAMESPACE}
    label:
      app: wheel-agent
    roleRef:
      name: self-access-reviewer
    subjects:
      - kind: ServiceAccount
        name: wheel-agent
        namespace: ${AGENT_NAMESPACE}
  - apiVersion: authorization.openshift.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: self-provisioner-${AGENT_NAMESPACE}
    label:
      app: wheel-agent
    roleRef:
      name: self-provisioner
    subjects:
      - kind: ServiceAccount
        name: wheel-agent
        namespace: ${AGENT_NAMESPACE}
  - apiVersion: authorization.openshift.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: system:basic-user-${AGENT_NAMESPACE}
    label:
      app: wheel-agent
    roleRef:
      name: system:basic-user
    subjects:
      - kind: ServiceAccount
        name: wheel-agent
        namespace: ${AGENT_NAMESPACE}
